export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const CHECK_USER = 'CHECK_USER';
export const SIGN_ERROR = 'SIGN_ERROR';

export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const READ_CAMPAIGNS = 'READ_CAMPAIGNS';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';

export const CREATE_QUEST = 'CREATE_QUEST';
export const READ_QUESTS = 'READ_QUESTS';
export const UPDATE_QUEST = 'UPDATE_QUEST';
export const DELETE_QUEST = 'DELETE_QUEST';
